.TH CEPL: "7" "June 2017" "cepl: CEPL v0.8.3" "User Commands"

.SH "NAME"
cepl \- a C11 Read-Eval-Print Loop

.SH "SYNOPSIS"
.sp
.nf
\fIcepl\fR [\-hpvw] [\-c<compiler>] [\-l<library name>] [\-I<additional header directory>] [\-o<output.c>]
.fi

.SH "DESCRIPTION"
.sp
CEPL is a command-line, interactive C11 Read-Eval-Print Loop, useful for instantaneous prototyping, mathematical calculations, and
general algorithm exploration.

.SH "USAGE"
.sp
CEPL currently supports multiple compilers, readline key-bindings/tab-completion, and the ability to specify additional shared libraries to link against.
.sp
A list of completions can also be optionally generated for each shared library if “\fBnm\fR” and “\fBperl\fR” are present.

.SS "COMMANDS"
.sp
Input lines prefixed with a “\fB;\fR” are used to control internal state.

.HP
\fB;f[unction]\fR:	Define a function (e.g. “\fB;f void foo(void) { … }\fR”)
.HP
\fB;p[arse]\fR:		Toggle -p (shared library parsing) flag
.HP
\fB;q[uit]\fR:		Exit CEPL
.HP
\fB;r[eset]\fR:		Reset CEPL to its initial program state
.HP
\fB:w[arnings]\fR:	Toggle -w (warnings) flag

.SS "OPTIONS"
.sp
Command line options:

.HP
\fB\-h\fR,\fB\-\-help\fR:	Show help/usage information.
.HP
\fB\-p\fR,\fB\-\-parse\fR:	Add symbols from dynamic libraries to readline completion.
.HP
\fB\-v\fR,\fB\-\-version\fR:	Show version information.
.HP
\fB\-w\fR,\fB\-\-warnings\fR:	Compile with “\fB\-pedantic\-errors\fR \fB\-Wall\fR \fB\-Wextra\fR” flags.
.HP
\fB\-c\fR,\fB\-\-compiler\fR:	Specify alternate compiler.
.HP
\fB\-l\fR:			Link against specified library (flag can be repeated).
.HP
\fB\-I\fR:			Search directory for header files (flag can be repeated).
.HP
\fB\-o\fR:			Name of the file to output source to.

.SH "AUTHOR"
.sp
Joey Pabalinas <alyptik@protonmail.org>

.SH "NOTES"
.sp
https://github.com/alyptik/cepl
